import React, { Component }  from 'react';
import img1 from "./images/news_timeline1.jpg";
import img2 from "./images/news_timeline2.jpg";
import img3 from "./images/news_timeline3.jpg";
import img4 from "./images/news_timeline5.jpg";
import behind1 from "./images/behind1.jpg";
import behind2 from "./images/behind2e.jpg";
import sunnies1 from "./images/sunnies1.jpg";
import sunnies1e from "./images/sunnies1e.jpg";
import sunnies2 from "./images/sunnies2.png";
import fenton1 from "./images/fenton1.jpg";
import fenton2 from "./images/fenton2.jpg";
import fenton3 from "./images/fenton3.jpg";
import alook1 from "./images/alook1.png";

const content = [
  {
    title1: "Timeline of",
    title2: "the Willard Straight",
    title3: "Hall Takeover",
    title: "Timeline of the Willard Straight Hall Takeover",
    title_caption: "By Yuichi Kakutani",
    parallax1: img1,
    sketch_caption: "Header Photo Courtesy of Fenton Sands '70",
    large_letter1: "R",
    p1: "oughly three months after the enactment of the landmark 1963 Civil Rights Act, a Princeton-educated academic began his tumultuous tenure as Cornell’s seventh university president. Until he resigned from his position six years later, President James A. Perkins presided over an increasingly racially-charged campus that struggled to accommodate the rapid influx of African American students.",
    p2: "In 1965, Perkins, a firm believer in racial integration, set up the Committee on Special Education Projects, a minority recruiting program that aspired to make Cornell accept more \“qualified students who have been disadvantaged by their cultural, economic and educational backgrounds.\” ",
    p3: "The committee’s recruiting efforts led to a dramatic rise in African American enrollment. When Perkins arrived on campus, Cornell had less than 20 African American students, mostly from middle class backgrounds, out of a student population of more than 4,000. By Fall 1968, the University had 250 African American Cornellians, many from Northern cities and the South. That was a 1250 percent increase.",
    p4: "Cornell struggled to respond to the sudden influx of people of color into campus. While fraternities created a special committee to help black students rush fraternities, the Phi Delta Theta fraternity in Fall 1966 charged some black students for entry into a party while letting their white classmates in for free. The campus store did not sell any makeup suitable for black women, or books and many other items used by African Americans.",
    p5: "Partially as a result of the insufficient accommodation for them, many African Americans felt like Cornell was trying to assimilate them into white culture at the expense of their black identity. \“I think they want us to get into this \‘mainstream\’ thing. They figure that after four years up here in this isolated world, you’ll go back and fall into your $20,000 a year job and never think twice,\” said Earl M. Armstrong \’69, then a successful biochemistry student.",
    quote1: "Many African Americans felt like Cornell was trying to assimilate them into white culture at the expense of their black identity.",
    p6: "In response to these and many other instances of racial friction, in 1966, some black students founded the Afro-American Society, a predominantly black group that stated it aimed to spread factual information about black history and fight \“social, economic and psychological conditions which blight the lives of black people.\” ",
    image1: img2,
    quote2: "",
    quote2_1: `Members of Delta Upsilon fraternity are repulsed after attempting to break into the Straight. Richard A. Schulman \’71 / Sun File Photo`,
    p7: "The group initially attracted only a small following. But two years later, many more black Cornellians became convinced that the University was not fostering a racially equitable campus that accommodated their needs, joining AAS in troves.",
    image2: img3,
    quote3_1: "After the failed incursion, the black occupiers made the decision to smuggle in guns for protection. They are seen here assembling in the main lobby prior to exiting the building. Courtesy of Fenton Sands ’70",
    p8: "As the AAS rose in popularity, and more black students were admitted to Cornell, high-profile racial incidents became increasingly common in the one-year period leading up to the takeover.",
    p9: "In April 1968, roughly 50 AAS members took control of the economics department to protest a visiting lecturer, Father Michael McPhelin, who they said was perpetuating \“institutional racism.\” ",
    p10: "Phelin, who lectured about poverty in the United States, sometimes implied that the U.S. poor lacked the necessary drive and ambition to succeed.  While Phelin was not explicitly discussing poor blacks during his lectures, some of the African American students in the classroom argued that he implicitly was, motivating them to demand his removal and replacement by a black professor. ",
    p11: "The demands went unmet and the students soon vacated Goldwin Smith Hall, where the economics department was located then.",
    quote4: "The AAS published a statement in March 1969 denouncing the board for engaging in \“selective political intimidation.\”",
    p14: "Several high profile incidents will follow the economics department takeover. In December of that year, seven black students with toy guns caused commotion in the Ivy Room. Two months later in February 1969, in the middle of a symposium on South Africa, two students jumped on stage, one of who grabbed President Perkins\’ collar as he was beginning to explain why Cornell invested in the Apartheid country. One month after that, two white students assaulted on the Arts Quad said their assailants were black.",
    p15: "The toy guns incident in particular provoked Cornell to impose penalties on those involved. The disciplinary board at the time repeatedly summoned the students, who did not attend the hearings because they considered it illegitimate. The AAS had published a statement in March 1969 denouncing the board for engaging in \“selective political intimidation,\” failing to include black board members and wrongfully judging \“political acts directed against the University administration.\” ",
    p16: "The board made their decisions anyway at two a.m. on April 18, convicting three black students for physical harassment. The other defendants who escaped conviction were all white.",
    p17: "Less than an hour after the conviction of the three African American students, members of the Wari House — an off-campus cooperative established at the request of AAS to accommodate African American women — saw a cross burning on their front porch. ",
    p18: "The next day, black students moved into Willard Straight Hall.",
    p19: "Around 5:30 a.m. on April 19, about 100 black students began barricading the exits of Willard Straight Hall, which was hosting Parent’s Weekend guests. By 6:16 a.m., they had evicted all the parents and employees in the building under the coordination of the AAS.",
    p20: "The students assumed control of the building in a peaceful manner, according to Edward L. Whitfield ’70, then-president of AAS. ",
    p21: "\“We asked the janitors to sit down for awhile. We told them if they had any duties before they left the building, they should do them. Like if they had to call the police, they should call them. … They said, \‘Yes we do have to call the police, but we don’t want to do it because you all seem like a nice group of fellows\’,\” Whitfield later told a group of Cornell alumni.",
    parallax2: img4,
    parallax2_1: "After exiting the Straight, the protestors march to the front steps of 320 Wait Ave, where they read out a compromise they have reached with the administration",
    parallax2_2: " | Larry Baum ’72 / Sun File Photo",
    large_letter5: "A",
    p22: "s nearly 50 members of the Students for a Democratic Society, a prominent student organization involved in the civil rights movement with branches in many U.S. campuses, surrounded the Straight in solidarity, the University considered obtaining a court injunction to eject the occupants, telling them at 9:15 a.m. that they would be guilty of trespassing if the occupation continues. ",
    p23: "Twenty minutes later, 20 to 25 fraternity brothers, most from Delta Upsilon, entered the Straight from a broken window. Then DU President Thomas MacLeod \’70 said that the brothers entered the building because they \“just wanted to open lines of communication with the black athletes.\” The occupiers almost immediately pushed out the brothers from the building, but soon received reports that some fraternity members \“were discussing whether or not to attack us,\” according to Tom Jones \’69 M.A. \’72, a student leader involved in the takeover.",
    p24: "A trustee committee investigating the takeover later concluded that the occupiers had heard several threatening rumors while they held the Straight, including reports that there was a bomb in the building, someone was conspiring to burn the Wari house, and a group of drunk fraternity brothers were collecting arms to \“get back their building.\”",
    p25: "These concerns motivated the black students to receive firearms from their supporters outside during the evening of that day. In total, the students armed themselves with 17 rifles and shotguns, along with stashes of ammunition. While guns were not banned from campus at this point, the introduction of firearms to campus politics shocked President Perkins, who said that it was \“a shattering experience. The guns were not justified.\” ",
    p26: "The stalemate persisted into the next morning, when administrators met with an unarmed Whitfield and several other AAS representatives in the foyer of the Straight. There, black students said the University had to, among other demands, nullify its conviction of those involved in the toy gun incident and begin an investigation into the cross-burning at Wari House. The negotiation continued until 2 p.m. when Whitfield agreed to soon leave the building. The students later left with guns still in hand, despite Cornell’s requests to vacate the Straight unarmed.",
    p27: "At 4 p.m., April 20, the African American students, still equipped with bandoliers and firearms, left the Straight to cheering crowds. Steve Starr of The Associated Press photographed the dramatic exit of one of the students, AAS leader Eric Evans \’69, and received a Pulitzer prize for it.",
    p28: "As condition for the students\’ withdrawal from the building, the University agreed to investigate the cross burning and recommend the nullification of the toy gun incident convictions at a faculty meeting. It also agreed to help the students find legal help if they later faced civil charges, but declined to pay for it. In turn, African American students agreed to help build a new judiciary system that AAS would consider legitimate.",
    p29: "The campus controversy, however, was not over. 40 professors, mostly in the government and history departments, threatened to resign if the charges from the toy gun incident were nullified. It took an intervention from Perkins to have the faculty agree to rescind the reprimands. Several professors and administrators still resigned. ",
    p30: "While he initially signaled his intention to stay in office despite the incident, Perkins also resigned several weeks after the takeover as alumni and faculty criticized his handling of the occupation.",
    p31: "The events immediately following the occupation had significant effects on Cornell’s shared governance. An impromptu group composed of thousands of faculty members and students in Barton Hall began discussing a wide range of issues from racism to academic freedom. The group later helped reform the student judiciary system and set up Cornell’s first shared governance institution, the University Senate.",
    p44: "Yuichi Kakutani is a member of the Class of 2019 in the College of Arts and Sciences. He was a News Editor on the 136th editorial board and can be reached at ykakutani@cornellsun.com."
    }, 
    {
      title1: "Behind the Pulitzer",
      title2: "Prize-Winning Photograph",
      title: "Behind the Pulitzer Prize-Winning Photograph",
      title_caption: "By Amina Kilpatrick",
      parallax1: behind1,
      large_letter1: "I",
      p1: "n April of 1969, Steve Starr was a young photojournalist working out of the Associated Press\’s Albany office. He had graduated from college in San Diego, spending his later school years working as a full-time photographer at the local newspaper. ",
      p2: "Starr originally got into photography in highschool when his school newspaper, where he served as editor, did not have a photographer. This translated into a life-long love of photographing moments and people, working full time as a college student for the local news paper, extending his undergraduate time to five years. The years paid off because Starr was immediately hired by the Associated Press, a national news organization — his dream.",
      p3: "After interning in the New York office for his first year, Starr was sent to Albany. Prior to the Willard Straight Hall takeover, he had seen many college campuses and their protests. The 1960s marked a tumultuous time in American history as young people protested the war in Vietnam, the ongoing Civil Rights Movement and increasing diversity on college campuses. ",
      p4: "\“Because I am young and available all the time, I was the photographer they sent to demonstrations. I had been to Yale, It seem[ed] like I was doing a demonstration every single month.\” ",
      p5: "Students pushing back against the administration was not foreign to Starr.",
      quote1: "Starr was immediately hired by the Associated Press.",
      p6: "\“You really have to live into 1968 and 1969. In 1968, Martin Luther had been assassinated, Bobby Kennedy is assassinated, this crazy guy Nixon is elected… It’s almost hard to explain,\” he said.",
      image1: behind1,
      quote2_1: "The Newsweek cover featuring the Pulitzer-winning photograph by Steve Starr.",
      p7: "On the morning of the Takeover, Starr got a call notifying him to get to Ithaca — immediately. He heard there was a protest going on at Cornell.",
      // image2: behind2,
      // quote3_1: "The photographer as a young man. | Courtesy of Steve Starr",
      p8: "He spent most of his time in the Cornell Public Relations office, learning information sparingly as they wished to share it as the situation escalated. However, once Starr was tipped that there were guns on campus, he was stunned. ",
      p9: "Starr likened the revelation to seeing spaceships — that was how unbelievable the notion was.",
      p10: "\“Our basic reaction was, you got to be kidding,\” Starr said. ",
      p11: "Once Starr saw one guy with a gun and was able to verify that a least a portion of the tip was true, he sprung into action. Unlike the other protests Starr had covered at the time, there was the introduction of the weapons.",
      quote4: "There had never been guns in a black protest.",
      p14: "\“To have guns on campus, had never happened at that point. There had never been guns in a black protest, it would run counter to the MLK non-violent narrative,\” Starr said. \“The reporter and I are very much aware of that and we are discounting the fact that there are guns. \“",
      p15: "On Sunday, the day the students finally left the building, Starr positioned himself and caught the first moments of students leaving the Straight. Immediately that night, Starr sent the photo through the A.P. wire service to news organizations across the country. A viral image was born. ",
      p16: "The widespread impact of the photo was in large part due to Starr’s affiliation with the Associated Press and the mechanism they had to share information. Similar photos taken of the situation did not get the same reaction. ",
      p17: "Starr believes the photos had such a great impact due to the incredulity of guns on campus for a protest.",
      p18: "\“My take is that to white America, the notion that blacks are going to fight back was an electrifying and terrifying moment,\” Starr said. \“You all add in the factor that these particular blacks folks are admitted to an elite Ivy League university — why the heck are they carrying guns and fighting back?\”",
      p19: "The social environment at the time largely shaped the public’s reaction to the image, Starr said.",
      p20: "\“There is this whole 1960 narrative that the country is coming unglued and there is violence and racial demonstrations everywhere,\” he recalled. \“At that particular time, the picture electrified the country.\”",
      p21: "Fortunately for Cornell’s situation, the students and the administration worked to deescalate the situation before it led to bloodshed. ",
      parallax2: behind2,
      parallax2_1: "The photographer as a young man.",
      parallax2_2: " | Courtesy of Steve Starr",
      p22: "On the day Starr received his Pulitzer for the award-winning photograph a year after the takeover, four students were murdered at Kent State during the Vietnam War protests. Kent State was a reminder of what Cornell could have been.",
      p23: "Starr maintains, though, that the important part of the story are the people and the situation in the photograph, not the photographer.",
      p24: "\“I am the messenger, not the message,\” he said. \“It is a civil rights story, it is a black guy story.\”",
      p25: "As Starr reflected on his career and the takeover, he addressed — and lamented — the current state of journalism. ",
      p26: "\“How in the world you are going to report the news? Visual journalist[s] are going to have an influence in this radically changed environment where everybody in the world can take a picture and video, newspapers are contested as fake [and] newspapers are dying?\” Starr asked. ",
      p27: "Tom Jones \‘69 a black student who participated in the takeover, is the subject of the photo where he is raising his fist in a black power salute. He told The Sun that he was conscious of the image he was creating and the actions he was taking. He purposefully was the last person leaving the building, carrying three levels of weapons, giving the image that he was ready to fight.",
      p28: "\“I was very conscious of the symbolism of the photo in the context of the Straight that caused us to bring in the guns. It was only after the vigilantes from Delta Upsilon that came into the Straight,\” Jones said. \“They were going to throw us out.\”",
      p29: "\“It was only then that we brought in the guns,\” Jones said. ",
      p30: "Jones said that black people had been terrorized by others for centuries. The statement he wanted to make was that there was a new generation of black people that would not be terrorized.",
      p31: "\“The black power salute, we are the generation of African Americans that is not going to be intimidated,\” Jones stated. \”That’s what I was feeling, and that's how I looked in the photo — they captured it perfectly.\”",
      p44: "Amina Kilpatrick is a member of the Class of 2021 in the College of Arts and Sciences. She is a News Editor on the 137th editorial board and can be reached at akilpatrick@cornellsun.com.",
    },

    {
      title: "Sunnies Recall The Sun's Coverage of the Takeover",
      title_caption: "By Maryam Zafar and Amina Kilpatrick",
      parallax1: sunnies1e,
      large_letter1: "A",
      p1: "s national reporters from the country’s leading papers flocked to Ithaca, student reporters found themselves both under spotlight and thrust behind the pen. A departure from The Sun’s typical campus role, during the times surrounding the black students’ occupation of Willard Straight Hall, the newspaper was no longer reporting only for the Ithaca community.",
      p2: "\“It was just so exciting. You were at the center of the world,\” Stanley Chess \’69 said. Chess, who was a senior at the time of the Takeover, had finished his term as editor in chief a few months before, reflected on the whirlwind of The Sun’s newsroom fifty years later. ",
      p3: "\“You'd be sitting there, working on a story, and next to you was a guy named Homer Bigart who was one of the famous reporters of the time from The New York Times,\” Chess recalled, chuckling. \“And he was working on the same story you were working on in the same newsroom, next to you.\” ",
      p4: "On April 20, 1969, when the famous front page was printed, the bylines of the reporters were students who were as young as sophomores, tasked with accurately communicating a rapidly-unfolding event to the country.",
      p5: "When working on stories, student reporters would head down to the Colonial Building in what is now the Ithaca Commons, producing a daily print paper while also enrolled in classes — technically. ",
      quote1: "\"It was just so exciting. You were at the center of the world.\"",
      p6: "\“We didn’t go to class a lot,\” Chess said. ",
      image1: sunnies1,
      quote2_1: "Escorted by Public Safety, the armed protesters march toward the Arts Quad, seen here from the roof of Olin library. | Sun File Photo",
      p7: "During the events of the takeover, Brian W. Gray ’71 M.A. ’74 noted that he was \“clued out\” from the issues at hand and was mainly focused on getting good shots. At the time, there was no digital photography and you couldn’t tell how your photos turned out prior to developing them.",
      image2: sunnies2,
      quote3_1: "Stan Chess \’69 (left) had just finished his term as editor in chief when the Takeover occurred. He was succeeded by Ed Zuckerman \’70 (right). Middle is Vivian Lam \’69, who served as business manager at the time. | Sun Clipping",
      p8: "\“I didn’t realize there was this black discontent … I was surprised at it,\” Gray shared. \“The black movement wasn’t particularly high on my radar.\”",
      p9: "He served as the photography editor at The Sun during the takeover. Prior to the events of the takeover, Gray was had previous experience covering protests of the Vietnam war and was even tear gassed in Washington, D.C. ",
      p10: "At the time, while covering racial tensions, The Sun’s news team was staffed primarily by white students, Chess said, which made finding and maintaining reliable sources difficult. \“I don’t remember if there was a black reporter,\” Gray recalled.",
      p11: "As a result, the news team incorporated an unusual source of information. ",
      quote4: "\“I don’t remember if there was a black reporter.\” ",
      p14: "\“Some woman called me up on The Sun when I was Assistant Managing Editor,\” Chess recalled, and offered him a perspective on a story that was going to be printed in the paper. In hindsight, Chess realized that her perspective had been accurate. ",
      p15: "Over time, through intermittent phone calls with the newsroom when notable events occurred, Chess said he and the news team continually used information that she provided, and never printed her name. ",
      p16: "He said that he could not recall her name fifty years later, and that he never met the woman, before or after his time at Cornell, but that he knew her name and that she was a black student at the time, and she offered insight and a perspective that The Sun did not have a source for. ",
      p17: "\“That was the contact that we were able to get information into The Sun that we would not have been able to get otherwise,\” Chess said. The published information was not contested, to Chess\’ recollection. ",
      p18: "\“It was a gamble,\” Chess said, but \“we had no choice.\” ",
      p19: "Sometimes, the news came at unexpected times. ",
      p20: "On the day of the takeover, Gray initially learned of the events during a night of partying. He recalled he was \“a little bit incapcitated\” and sent a photographer to capture the fraternity students trying to break into the Straight. ",
      p21: "Gray was the photographer behind a different set of iconic shot of the events, although his version did not win the Pulitzer Prize, while the Associated Press’ photographer did. The difference between The Sun and the prizewinning photograph was that in Gray’s photograph hangs the “Welcome Parents” banner, fossilizing the memory of the fateful parents weekend in his image. He also captures the first students walking out the building with guns in their hands.",
      parallax2: sunnies2,
      p22: "Gray recalled taking this photograph, and said he ran out of film that day because he taking photos of his friends earlier on.",
      p23: "After Gray graduated, he left the field of journalism. One his main reasons was how he felt that he was merely an observer of events, and could not contribute to direct action.",
      p24: "\“One of the reasons I quit journalism in the end was I felt that I spent all this time on the outside as a dispassionate observer and I was focused on not being involved [and] that was not something I wanted for the rest of my life,\” Gray said. \“That’s why I became a lawyer.\” ",
      p25: "Chess didn’t recall ever receiving heavy criticism for The Sun’s coverage of the takeover, but also noted that it was a time when there was generally more trust in the media, unlike today. ",
      p26: "\“Nobody prepared you,\” he said, about the contentiousness and tensions surrounding his time at Cornell, but that was the only college experience he knew.",
      p27: "During his time at Cornell, some of his classmates were drafted into the highly-controversial Vietnam War, protests and sit-ins were continual, a cross was burned on the grass outside and he witnessed a surreal moment as his classmates holding rifles walked out of Willard Straight Hall — where he would later live for a short period of time. ",
      p28: "\“It was a once-in-a-lifetime event,\” he said. ",
      p29: "\“I wasn’t afraid. I was never feared that there was going to be some kind of horrible violence occurring,\” Gray told The Sun. \“These things have never happened before and we didn’t have these mass shootings that happen now.\”",
      p30: "When reflecting, Gray noted that there were things he might have done differently. ",
      p31: "\“I was very naively unpolitical. I had worked for the Smithsonian institution for 2 summers. I was focused a lot of that, not on the politics of anything.\”",
      p32: "The Sun, Gray said, could have been more proactive in its reporting and reached out instead of simply observing. ",
      p33: "\“In fact I understand from the New York Times article that was there about 10 years ago, one of the black guys has the picture I took framed,\” Gray noted. \“I have never spoken to any of them that I know of, I never spoke to them at the time.\”",
      p34: "Gray attributed this sense of distance to his decision to quit journalism and become a lawyer, as he currently works in Canada, a job that gave him more of an avenue for action than journalism. ",
      p35: "\“You don’t control your images, you don’t control what people take from them,\” Gray said.",
      p44: "Maryam Zafar is a member of the Class of 2021 in the College of Arts and Sciences. She is the City Editor on the 137th editorial board and can be reached at mzafar@cornellsun.com. Amina Kilpatrick is a member of the Class of 2021 in the College of Arts and Sciences. She is a News Editor on the 137th editorial board and can be reached at akilpatrick@cornellsun.com.",
    },
    {
      title: "Fenton Sands ’70 Documented Black Student Life at Cornell",
      title_caption: "By Amina Kilpatrick",
      parallax1: fenton1,
      large_letter1: "F",
      p1: "Fenton Sands ’70 shared his photos — often documenting the black community because other people weren’t —  with The Sun, offering a unique vantage point into the Takeover through the eyes, and lens, of a black student at Cornell from the time.",
      p2: "At the time of the Takeover in 1969, Ithaca was relatively isolated from major news outlets. Until the famous photo of students walking out of Willard Straight Hall with guns was published on front pages across the country, few photographers were documenting the Takeover. ",
      p3: "Sands, however, was. He was a known student-photographer at the time, and Sands’ photos had appeared in The Sun multiple times when he was a student at Cornell.",
      p4: "During the takeover, Sands was inside the building. He documented the life of students and the actions before the events themselves. Unlike other photographers, his familiarity with his fellow students could be seen in the casualness of the subjects in the photos. Students are smiling and posing, and many appeared unbothered by the presence of the camera.",
      p5: "\“Black students knew I took a lot of pictures,\” Sands told the Sun. \“They weren’t bothered or threatened by me taking pictures because they were so used to that.\” ",
      quote1: "\“Black students knew I took a lot of pictures.\”",
      p6: "\“That clearly would have made a big difference,\” Sands added.",
      image2: fenton2,
      quote3_1: "The photographer as a college student. | Courtesy of Fenton Sands ’70",
      p7: "After the Takeover, international news outlets reached out to Sands to share these photos. While Sands obliged, he told The Sun that editing techniques were used to mask the identity of individuals presented in Life Magazine.",
      image1: fenton1,
      quote2_1: "After getting ready to leave on the first day, a warning was expressed at this meeting that going out might subject students to attack. The occupiers decided to stay overnight. | Courtesy of Fenton Sands '70",
      p8: "In the years following the Takeover, the question of punishing students for their participation was not decided. Several students had been indicted by New York State. Sands shared his photos on the condition of students not being recognizable out of fear that they would be used as evidence.",
      p9: "Additionally, Sands has since shared his work in the 2016 Agents of Change film. The photos showcase not only what happened after the students left the building with guns but also the planning that led up to the decision. ",
      p10: "Sands graduated from Cornell in 1970, a year after the Takeover, with a degree in Agricultural Economics. He received his Ph.D. from Michigan State University in Agricultural Economics. After that, he spent decades working for United States Agency for International Development following in the footsteps of his father, who also attended Cornell.",
      quote4: "Sands shared his photos on the condition of students not being recognizable.",
      parallax2: fenton3,
      parallax2_1: "Occupiers watch as campus police (then called public safety) assembled outside the Straight.",
      parallax2_2: " | Courtesy of Fenton Sands '70",
      p44: "Amina Kilpatrick is a member of the Class of 2021 in the College of Arts and Sciences. She is a News Editor on the 137th editorial board and can be reached at akilpatrick@cornellsun.com.",
    },
    {
      title: "A Look Into the National News Coverage of the Occupation",
      title_caption: "By Kathryn Stamm",
      parallax1: alook1,
      large_letter1: "T",
      p1: `The Willard Straight Hall Occupation — described in 1999 by former professor Thomas Sowell as \“${<a href="https://www.hoover.org/research/day-cornell-died">the day Cornell died</a>}the day Cornell died\” — symbolized an era of national change and turmoil, full of questions about race. As the country turned their attention to the events unfolding in Ithaca in the following weeks, major news organizations often painted the event as violent and centered their narratives on the resulting white fear. `,
      p2: "Pictures of armed black students marching across campus plastered national newspapers, underscored by headlines about a violent crisis, likening the occupation to a battle in a war. However, when the black occupants initially entered the Straight, they were unarmed and no one was reported injured. ",
      p3: "On April 19, 1969, at 5:30 a.m., approximately 100 African-American students occupied Willard Straight Hall, ejecting 40 staff members and 30 Parents’ Weekend visitors by shouting “Fire!” The Sun previously reported. ",
      p4: "This occurred in the midst of one of the most racially difficult times on the Hill. In the fall of 1968, there were 250 black students on the campus of 14,000 — an increase from fewer than 20 in 1963. ",
      p5: "The occupation was largely a response to various racist incidents on campus that year. The Phi Delta Theta fraternity charged some black students to attend a dance without charging white students a fee. In response to an “intolerably hostile atmosphere of the dorms,”  the University created a black woman’s co-op, called Wari House. The day before the occupation, a flaming cross was found on their porch.",
      quote1: "When the black occupants initially entered the Straight, they were unarmed and no one was reported injured.",
      p6: "Though the occupants entered unarmed, they sought protection in the form of obtaining 17 rifles and shotguns from black students outside the Straight between 9:45 and 10 p.m. This came as a response to rumors that white fraternity brothers were planning to attack. Following the arming of the students, the University administration began negotiations, first over the phone with Edward Whitfield ’71.",
      image1: alook1,
      quote2_1: "A news camera captures a speech given to the Barton Hall community. | Sun File Photo", 
      p7: "On April 20, 1969 at 4:13 p.m., the front doors of Willard Straight Hall opened. Students emerged after occupying the building for 35 hours. The 110 black students — some with ammunition strapped to their bodies and carrying rifles and shotguns — then marched through the Arts Quad to the AAS headquarters on North Campus to sign a seven-point agreement responding to the campus issues of race. ",
      p8: "This is where the Newsweek story began: at 4:13 p.m., after the first 35 hours of the occupation and the prior months of racial unrest. ",
      p9: "Further, the picture most associated with the event in nationwide publications was of the students exiting the building to sign. Taken by Associated Press photographer Steve Starr, the Pulitzer Prize-winning photograph was often paired with captions and headlines describing the students singularly as armed. ",
      p10: "The May 5, 1969 edition of Newsweek — a weekly magazine whose editions featured the prominent news stories of that week — offered the caption “Universities Under the Gun: Militants at Cornell” with that picture, on the cover.",
      p11: "\“Armed Negroes End Seizure, Cornell Yields,\” read The New York Times front-page article headline on April 21, 1969. ",
      quote4: "\“The Negro students left the litter of their occupation in Straight Hall.\”",
      p14: "The New York Times also focused on the physical aftermath of the event, despite the fact that the only injuries were minor, and a result of a fist-fight that broke out when white fraternity members attempted to break back in, before the guns arrived. ",
      p15: "“The Negro students left the litter of their occupation in Straight Hall,” it reported. “Mattresses and cushions had been pulled into the cafeteria where most of the students slept. In the Memorial Room, some high light fixtures had been ripped out, several candy machines had been rifled and walls bore slogans like ‘Kill the fraternity honkies’.”",
      p16: "The Newsweek article follows its description of the students “some draped with bandoliers and carrying an arsenal of seventeen rifles, shotguns and homemade spears” with the reaction from a white student. ",
      p17: "“When they stepped out and I saw the ammunition on the belts and the rifles, my heart dropped to my toes,” Lawrence Terkel, a white Cornell senior, said to Newsweek.",
      p18: "“This profound consternation was shared by almost everyone associated with Cornell — the faculty, the students, militant and uninvolved, parents and alumni,” Newsweek continued. “Moreover, it radiated beyond Cornell to every other U.S. campus and indeed beyond the universities to U.S. society as a whole.”",
      p19: "Ultimately, Newsweek glossed over the roots of the occupation in offering an explanation to why the black students armed, undermining the fear of attack by their white classmates. “Others, with a psychological bent, held that the blacks were mainly on a self-fueled ‘ego trip,’ and were asserting their masculinity — and no doubt there was some truth in that, as well,” it reported. ", 
      p20: "At least half of the occupants were women, though — a detail that escaped many major outlets’ reporting — according to Juanita Goss ’72, one of the participants.",
      p21: "Ultimately, the media response to the Willard Straight Hall occupation — its sentiment that the event was violent, catastrophic, and perhaps unnecessary — is summed by Newsweek. “The traumatic events at Cornell took place in a week when the U.S. campus seems to have turned into a national battleground.” ",
      parallax2: behind1,
      parallax2_1: "The famous Newsweek Magazine cover. ",
      p44: "Kathryn Stamm can be reached at kstamm@cornellsun.co",
    },
  ];

export default content;
