import hero1 from "./image/hero1.png";

const content = [
  {
    title1: "Timeline of",
    title2: "the Willard Straight",
    title3: "Hall Takeover",
    title: "Timeline of the Willard Straight Hall Takeover",
    title_caption: "By Yuichi Kakutani",
    parallax1: hero1,
    sketch_caption: "Header Photo Courtesy of Cornell University",
    large_letter1: "R",
    p1: "oughly three months after the enactment of the landmark 1963 Civil Rights Act, a Princeton-educated academic began his tumultuous tenure as Cornell’s seventh university president. Until he resigned from his position six years later, President James A. Perkins presided over an increasingly racially-charged campus that struggled to accommodate the rapid influx of African American students.",
    p2: "In 1965, Perkins, a firm believer in racial integration, set up the Committee on Special Education Projects, a minority recruiting program that aspired to make Cornell accept more \“qualified students who have been disadvantaged by their cultural, economic and educational backgrounds.\” ",
    p3: "The committee’s recruiting efforts led to a dramatic rise in African American enrollment. When Perkins arrived on campus, Cornell had less than 20 African American students, mostly from middle class backgrounds, out of a student population of more than 4,000. By Fall 1968, the University had 250 African American Cornellians, many from Northern cities and the South. That was a 1250 percent increase.",
    p4: "Cornell struggled to respond to the sudden influx of people of color into campus. While fraternities created a special committee to help black students rush fraternities, the Phi Delta Theta fraternity in Fall 1966 charged some black students for entry into a party while letting their white classmates in for free. The campus store did not sell any makeup suitable for black women, or books and many other items used by African Americans.",
    p5: "Partially as a result of the insufficient accommodation for them, many African Americans felt like Cornell was trying to assimilate them into white culture at the expense of their black identity. \“I think they want us to get into this \‘mainstream\’ thing. They figure that after four years up here in this isolated world, you’ll go back and fall into your $20,000 a year job and never think twice,\” said Earl M. Armstrong \’69, then a successful biochemistry student.",
    quote1: "Many African Americans felt like Cornell was trying to assimilate them into white culture at the expense of their black identity.",
    p6: "In response to these and many other instances of racial friction, in 1966, some black students founded the Afro-American Society, a predominantly black group that stated it aimed to spread factual information about black history and fight \“social, economic and psychological conditions which blight the lives of black people.\” ",
    image1: hero1,
    quote2: "Happening \"Today\"",
    quote2_1: "| Three weeks after first pumpkin sighting, the Today Show arrives in Ithaca to document the mysterious gourd. From the Tuesday, October 28, 1997 issue of The Cornell Daily Sun.",
    p7: "The group initially attracted only a small following. But two years later, many more black Cornellians became convinced that the University was not fostering a racially equitable campus that accommodated their needs, joining AAS in troves. ",
    p8: "As the AAS rose in popularity, and more black students were admitted to Cornell, high-profile racial incidents became increasingly common in the one-year period leading up to the takeover.",
    p9: "In April 1968, roughly 50 AAS members took control of the economics department to protest a visiting lecturer, Father Michael McPhelin, who they said was perpetuating \“institutional racism.\” ",
    p10: "Phelin, who lectured about poverty in the United States, sometimes implied that the U.S. poor lacked the necessary drive and ambition to succeed.  While Phelin was not explicitly discussing poor blacks during his lectures, some of the African American students in the classroom argued that he implicitly was, motivating them to demand his removal and replacement by a black professor. ",
    p11: "The demands went unmet and the students soon vacated Goldwin Smith Hall, where the economics department was located then.",
    quote4: "The AAS published a statement in March 1969 denouncing the board for engaging in \“selective political intimidation.\”",
    p14: "Several high profile incidents will follow the economics department takeover. In December of that year, seven black students with toy guns caused commotion in the Ivy Room. Two months later in February 1969, in the middle of a symposium on South Africa, two students jumped on stage, one of who grabbed President Perkins\’ collar as he was beginning to explain why Cornell invested in the Apartheid country. One month after that, two white students assaulted on the Arts Quad said their assailants were black.",
    p15: "The toy guns incident in particular provoked Cornell to impose penalties on those involved. The disciplinary board at the time repeatedly summoned the students, who did not attend the hearings because they considered it illegitimate. The AAS had published a statement in March 1969 denouncing the board for engaging in \“selective political intimidation,\” failing to include black board members and wrongfully judging \“political acts directed against the University administration.\” ",
    p16: "The board made their decisions anyway at two a.m. on April 18, convicting three black students for physical harassment. The other defendants who escaped conviction were all white.",
    p17: "Less than an hour after the conviction of the three African American students, members of the Wari House — an off-campus cooperative established at the request of AAS to accommodate African American women — saw a cross burning on their front porch. ",
    p18: "The next day, black students moved into Willard Straight Hall.",
    p19: "Around 5:30 a.m. on April 19, about 100 black students began barricading the exits of Willard Straight Hall, which was hosting Parent’s Weekend guests. By 6:16 a.m., they had evicted all the parents and employees in the building under the coordination of the AAS.",
    p20: "The students assumed control of the building in a peaceful manner, according to Edward L. Whitfield ’70, then-president of AAS. ",
    p21: "\“We asked the janitors to sit down for awhile. We told them if they had any duties before they left the building, they should do them. Like if they had to call the police, they should call them. … They said, \‘Yes we do have to call the police, but we don’t want to do it because you all seem like a nice group of fellows\’,\” Whitfield later told a group of Cornell alumni.",
    parallax2: hero1,
    parallax2_1: "",
    parallax2_2: "",
    large_letter5: "A",
    p22: "s nearly 50 members of the Students for a Democratic Society, a prominent student organization involved in the civil rights movement with branches in many U.S. campuses, surrounded the Straight in solidarity, the University considered obtaining a court injunction to eject the occupants, telling them at 9:15 a.m. that they would be guilty of trespassing if the occupation continues. ",
    p23: "Twenty minutes later, 20 to 25 fraternity brothers, most from Delta Upsilon, entered the Straight from a broken window. Then DU President Thomas MacLeod \’70 said that the brothers entered the building because they \“just wanted to open lines of communication with the black athletes.\” The occupiers almost immediately pushed out the brothers from the building, but soon received reports that some fraternity members \“were discussing whether or not to attack us,\” according to Tom Jones \’69 M.A. \’72, a student leader involved in the takeover.",
    p24: "A trustee committee investigating the takeover later concluded that the occupiers had heard several threatening rumors while they held the Straight, including reports that there was a bomb in the building, someone was conspiring to burn the Wari house, and a group of drunk fraternity brothers were collecting arms to \“get back their building.\”",
    p25: "These concerns motivated the black students to receive firearms from their supporters outside during the evening of that day. In total, the students armed themselves with 17 rifles and shotguns, along with stashes of ammunition. While guns were not banned from campus at this point, the introduction of firearms to campus politics shocked President Perkins, who said that it was \“a shattering experience. The guns were not justified.\” ",
    p26: "The stalemate persisted into the next morning, when administrators met with an unarmed Whitfield and several other AAS representatives in the foyer of the Straight. There, black students said the University had to, among other demands, nullify its conviction of those involved in the toy gun incident and begin an investigation into the cross-burning at Wari House. The negotiation continued until 2 p.m. when Whitfield agreed to soon leave the building. The students later left with guns still in hand, despite Cornell’s requests to vacate the Straight unarmed.",
    p27: "At 4 p.m., April 20, the African American students, still equipped with bandoliers and firearms, left the Straight to cheering crowds. Steve Starr of The Associated Press photographed the dramatic exit of one of the students, AAS leader Eric Evans \’69, and received a Pulitzer prize for it.",
    p28: "As condition for the students\’ withdrawal from the building, the University agreed to investigate the cross burning and recommend the nullification of the toy gun incident convictions at a faculty meeting. It also agreed to help the students find legal help if they later faced civil charges, but declined to pay for it. In turn, African American students agreed to help build a new judiciary system that AAS would consider legitimate.",
    p29: "The campus controversy, however, was not over. 40 professors, mostly in the government and history departments, threatened to resign if the charges from the toy gun incident were nullified. It took an intervention from Perkins to have the faculty agree to rescind the reprimands. Several professors and administrators still resigned. ",
    p30: "While he initially signaled his intention to stay in office despite the incident, Perkins also resigned several weeks after the takeover as alumni and faculty criticized his handling of the occupation.",
    p31: "The events immediately following the occupation had significant effects on Cornell’s shared governance. An impromptu group composed of thousands of faculty members and students in Barton Hall began discussing a wide range of issues from racism to academic freedom. The group later helped reform the student judiciary system and set up Cornell’s first shared governance institution, the University Senate.",
    p32: "",
    p33: "",
    p34: "",
    quote5: "",
    p35: "",
    p36: "",
    large_letter7: "",
    p37: "",
    p38: "",
    p39: "",
    p40: "",
    large_letter8: "",
    p41: "",
    p42: "",
    p43: "",
    p44: "Yuichi Kakutani is a member of the Class of 2019 in the College of Arts and Sciences. He was a News Editor on the 136th editorial board and can be reached at ykakutani@cornellsun.com."
    }, 
    {

    },
  
  ];

export default content;
