import hero1 from "./image/hero1.png";

const content = [
  {
    title1: "Any Person:",
    title2: "Willard Straight Hall",
    title3: "Takeover and Student Activism",
    title: "Any Person, Any Study: Willard Straight Hall Takeover and Student Activism",
    title_caption: "By Farhad Manjoo '00, former Sun editor in chief",
    parallax1: hero1,
    sketch_caption: "Header Photo Courtesy of Cornell University",
    large_letter1: "A",
    p1: "t first, I didn't really care about the pumpkin. No one did, not really.",
    p2: "Sure, it was curious -- suddenly one fall morning there was a tiny speck way at the top of the tall tower you walked by everyday. But it's not like it sparked an instant frenzy; you saw the speck and you maybe asked some friends about it, and one of them who'd heard from someone else would maybe say, \"oh yeah, it's a pumpkin, kinda weird,\" and then you'd think about it a minute and go, \"huh.\" And that was pretty much the whole story.",
    p3: "We were all very busy college kids, after all, but also: Those were different times! We didn't have phones! We couldn't snap pictures and create funny tweets and Stories and what-have-yous, we couldn't get the pumpkin on Reddit and BuzzFeed, sparking dumb posts about what Disney character the pumpkin resembled and whether the pumpkin was an alt-right meme yet.",
    p4: "Things didn't just become national news back then, is what I'm saying. It would take many days for most of Cornell and Ithaca to hear about the pumpkin on the top of the tower, and then weeks for the mystery to spread around the country. The first New York Times story about the pumpkin was published nearly three weeks after it was first spotted; after that, there were a few national spots, including the \"Today Show.\" You knew the pumpkin was something more than just a local curiosity once your parents started asking about it.",
    p5: "It was only as the attention grew -- and as the pumpkin kept clinging to the tower -- that people became really invested in the thing.",
    quote1: "You'd think about it a minute and go, \"huh.\" And that was pretty much the whole story.",
    p6: "Again, no phones! There wasn't a lot of other stuff competing for our attention. As you walked through campus you basically just looked around at the buildings and the sky and the other people.",
    image1: hero1,
    quote2: "Happening \"Today\"",
    quote2_1: "| Three weeks after first pumpkin sighting, the Today Show arrives in Ithaca to document the mysterious gourd. From the Tuesday, October 28, 1997 issue of The Cornell Daily Sun.",
    p7: "Day after day of these long, cold, Instagram-free-walks have a way of getting to you; eventually you find yourself getting lost in your own mind, and inevitably you ponder life's deepest mysteries. And in the fall of 1997, as you looked off into the distance every morning and kept catching that gourded steeple, one such mystery had to be, \"Wait, how the hell did they do that?\"",
    image2: hero1,
    quote3: "Splat",
    quote3_1: " | A botched attempt to remove the pumpkin results in mashed squash. From the Monday, March 16, 1998 issue of The Cornell Daily Sun.",
    large_letter2: "T",
    p8: "wenty years later, I still wonder. A couple years after the pumpkin prank, when I was a senior and editor of The Sun, I got an email from an anonymous source who claimed to know how the pumpkin got up there. My report on his account -- first published in the 2000 Senior Issue -- appears below.",
    p9: "I believe his story, but the source didn't give me the names of pranksters, including the name of the ringleader. So the mystery is still unsolved.",
    p10: "But you know what's awesome about today, versus 1999? Exactly, viral true-crime podcasts! Remember \"Serial\"? I'm thinking same thing, but with the pumpkin and the tower; we can even find a way to weave Casper into the story somehow, if that will help with sponsorships.",
    p11: "Or wait, I've got a better idea. How about a viral hashtag that encourages the pranksters to confess? It's been 20 years. They pulled off the best prank Cornell has ever known. Decades later, we can finally let them take a bow for risking their lives to give us 20 years of lonely pondering. Pumpkin pranksters, tell us who you are! #PumpkinAmnesty!",
    quote4: "You knew the pumpkin was something more than just a local curiosity once your parents started asking about it.",
    p12: "Howdy -- I just laughed my ass off at the article y'all published on \"how the pumpkin got onto the tower.\" Nice piece of fiction and speculation. Would you like to know the REAL story?",
    p13: "-- Excerpt of an e-mail sent to The Sun, Oct. 26, 1999",
    large_letter3: "I",
    p14: "salivated after reading this message. Seriously. Because even though dozens of jokers mail The Sun every day claiming something grand, and even though -- as editor in chief of the paper -- I'd learned to discount such conjecture, there would be no better coup for The Sun than finding the Pumpkin Prankster. And I wanted the paper to expose the fellow during my term.",
    p15: "",
    p16: "",
    large_letter4: "B",
    p17: "",
    p18: "",
    p19: "",
    p20: "",
    p21: "",
    parallax2: hero1,
    parallax2_1: "",
    parallax2_2: "",
    large_letter5: "W",
    p22: "",
    p23: "",
    p24: "",
    p25: "",
    p26: "",
    p27: "",
    p28: "",
    p29: "",
    large_letter6: "T",
    p30: "",
    p31: "",
    p32: "",
    p33: "",
    p34: "",
    quote5: "",
    p35: "",
    p36: "",
    large_letter7: "O",
    p37: "",
    parallax3: hero1,
    parallax3_1: "",
    parallax3_2: "",
    p38: "",
    p39: "",
    p40: "",
    large_letter8: "I",
    p41: "",
    p42: "",
    p43: "",
    p44: ""
    }, 
    {

    },
  
  ];

export default content;
