import hero1 from "./image/hero1.png";

const opedscontent = [
  {
    title1: "Excerpt from April 24, 2019",
    title2: "Tanenbaum Lecture",
    title3: "at Cornell University",
    title: "Excerpt from April 24, 2019 Tanenbaum Lecture at Cornell University",
    title_caption: "By Tom Jones '69",
    parallax1: hero1,
    sketch_caption: "Graphic by Daniel Ra grad",
    large_letter1: "F",
    p1: "ifty years ago I was an angry young man in my senior year at Cornell University. Mentally and emotionally I was prepared to be one of those African-Americans who would meet my destiny in a struggle against oppression and injustice that was much larger than any one of us, and even much larger than all of us. I thought we were the generation fingered by history to draw the line on America’s ill treatment of its black population. It had to stop with us, in our time.",
    p2: "As I reflect from the perspective of 50 years on the events at Cornell University in April 1969, I feel both regret and pride. I have regrets regarding the individual toll of those events. I’m sorry at the individual level of the people who were hurt. That includes black students who were traumatized; President Perkins who became the scapegoat for the wrath of angry trustees, faculty, and alumni; and professors and their families who were frightened by my angry rhetoric and the spectre of armed students on campus. But I’m not sorry at the institutional level, the broadest of which is the events at Cornell in the context of the racial discrimination and oppression and violence against African-Americans which was common in America at that time. I’m proud that we black students armed ourselves and said, in effect, “we are the generation of African-Americans who will not be intimidated by vigilantes”. The lesson here is that some life situations do not lend themselves to simplistic judgements of who was right or wrong. Sometimes it’s not either right or wrong, it’s both. I was right in April 1969 because our cause was just in fighting a racist society. But I was also wrong because my tactics caused harm to some individuals. I’ve wrestled my entire adult life with this moral ambiguity of April 1969 at Cornell University.",
    p3: "We should remember that 50 years ago America was still engaged in an unresolved battle to secure equal treatment for black Americans in public accommodations, employment, housing, voting, and other civil rights. De jure segregation was enshrined in the law in many states, and de facto institutional discrimination was the social norm throughout America. The petty discrimination of being denied access to public facilities was intended to dehumanize African-Americans, and to proclaim every day that we were different and inferior. The systemic institutional denial of economic opportunities ensured that African-Americans remained poor and powerless. Each previous decade of American history was more brutal in its treatment of the black population. That’s why I’m proud that my colleagues and I had the courage to say that the oppression and intimidation of African-Americans would stop with our generation, and we were prepared to fight about it.",
    p4: "The purpose of reciting this history is not just to remind us of where we have been, but also to focus on how far we have come. There is no point in suffocating our potential for today and tomorrow with irreconcilable animosity over the grievances of the past. The burden is too heavy, and we cannot change the past. That’s why I believe that just as a family cannot heal unless it lets go of yesterday’s anger, so all Americans of every race and creed and ethnicity should be open to reconciliation and healing, otherwise we will never achieve our full potential as a multiracial, multiethnic, and religiously diverse democracy.",
    p5: "Historical reflection also seems to make an undeniable case that African-Americans, other minorities, women, and the LGBTQ community have widespread educational, economic, and social opportunities today which are unprecedented in American history. Does this mean that America has overcome its historical problems? Of course not! The legacy of hundreds of years of slavery and the related physical and psychological barbarity against African-Americans created a scale of human misery and dysfunctionality which cannot be reversed or healed in just 50 years. But is America moving in the direction of civic equality and equal opportunity – unequivocally yes! This in no way diminishes the important work that Black Lives Matters and other groups do today to bring attention to ongoing police and vigilante violence against African-Americans, and widespread poverty among African-Americans. But we should acknowledge and celebrate the truth that for every incident of racial violence against African-Americans which occurs today, the frequency of such incidents was proportionately 50 times greater 50 years ago, and one 100 times greater one 100 years ago! We should acknowledge and celebrate the truth that many millions of African-Americans have lifted themselves out of poverty into the middle class and even higher. We should acknowledge and celebrate the truth that de jure discrimination against African-Americans is no longer enshrined in American law or the judicial system.",
    quote1: "You'd think about it a minute and go, \"huh.\" And that was pretty much the whole story.",
    p6: "So even as I am acutely aware of how far we have yet to go, I am enormously thankful for how far America has come in the past 50 years. I hope America continues this progress and becomes a country which respects and celebrates our diversity within the context of overarching bonds of community.",
    p7: "",
    large_letter2: "",
    p8: "",
    p9: "",
    p10: "", // Left of quote4. 
    p11: "", // Below Quote
    quote4: "",
    p12: "",
    p13: "",
    
    p44: "Thomas W. Jones ’69 was a spokesman for the Afro-American Society at the time of the Willard Straight Hall takeover. After graduating Cornell, he went on to serve as chairman and chief executive officer of Global Investment Management at Citigroup, president and chief operating officer of TIAA-CREF, and as a member of the Cornell Board of Trustees. He is the author of a memoir, From Willard Straight to Wall Street, published by Cornell University Press. "
  }, 
  {
    title1: "",
    title2: "Reflections on Cornell -",
    title3: "1969, Today and Beyond",
    title: "Reflections on Cornell – 1969, Today and Beyond",
    title_caption: "By Dr. Jacqueline Davis-Manigaulte",
    parallax1: hero1,
    sketch_caption: "Graphic by ___",
    large_letter1: "A",
    p1: "s was mentioned in the documentary Agents of Change, I was looking forward to the adventure of going to school away from home in the fall of 1968.  I immediately loved the beauty of the Cornell campus and was fortunate to have a great roommate — in fact we still keep in touch. I quickly made friends with all the students of color — our freshman class had the largest group of African-American and Latino students ever admitted to Cornell. However, in my courses there were never more than one or two African-American students, and sometimes there were none. With limited support from faculty or teaching assistants, there were many times when I felt invisible (and most of the classes were really large, which was also overwhelming). But I was a top student in high school and was determined to succeed at Cornell. So, I put in a lot of time at the library, found a solid study buddy, worked hard and actually graduated with honors.",
    p2: "It was a challenging time, especially for many African-American students who were experiencing difficulty dealing with faculty and courses that excluded or misrepresented African-American culture and history. These issues resulted in several demonstrations and the historic takeover of Willard Straight Hall in the spring of 1969. I participated in these events, as well as additional demonstrations when the first Africana Studies Center was destroyed by fire in the spring of 1970. Through these traumatic experiences I learned about the importance of standing up for issues that are important to you and your community.",
    p3: "The first Africana Studies Center at 320 Wait Avenue served as a place to obtain knowledge about African-American history and culture, and also as a place to connect and feel a true sense of belonging; we all need places where we feel grounded and can recharge to pursue our goals and dreams. The Africana Studies Center did that for me and my peers — it was a vital part of my existence at Cornell. It is where I got the support and validation — my home away from home. The establishment of the center was an indication that the University realized the need to invest in the success and well-being of African-American students.",
    p4: "By my junior year, a large number of students of color formed United Black Artists and shared their talents and creativity through a campus theatrical production entitled “To All Things Black and Beautiful,” under the direction of Professor Chestyn Everett.  Between studies, we rehearsed in the evening and on the weekends to create a very high quality production that included highlights from renowned African-American poetry, plays, music and dance. The production was well-received by our peers, the Cornell and Ithaca community, and was replicated the following year.  This experience reflected the need for Cornell to intentionally establish more bridges and supports for students of color as well as opportunities for engagement and interaction throughout the campus.",
    p5: "By the time my son Khalil arrived on campus in the early 90’s there were more supports. I had wanted him to be in a supportive learning environment, not experience the isolation and limited support I encountered at Cornell, and so he initially attended Morehouse College in Atlanta. However, he was already familiar with Cornell; he had attended several 4-H campus learning experiences, including a summer course through the Cooperative Extension 4-H Youth Development Program, and had come to CBAA reunions with me over the years. And so, after a year at Morehouse, he made the choice to transfer to Cornell.",
    quote1: "We all need places where we feel grounded and can recharge to pursue our goals and dreams.",
    p6: "By then, the University had established additional vehicles to support the interest of students of color such as the Third World Student Program Board, in which he participated as a member and officer, and other groups such as Black Student Union and the National Association of Black Engineers. He also resided in Ujamaa, which provided a rich and supportive environment in which he thrived.  Now there many additional programs that support students of color and other special interest groups.",
    p7: "Today, there are still demonstrations, sit-ins and rallies because there continue to be new issues and challenges we must face. As a society and a university, we take steps forward and back. What is required is that the University continue building bridges to understand, respect and provide opportunities for all members of the Cornell community. Some of today’s issues include mental health, sexual assault, ongoing micro-aggressions, unconscious bias, navigating first-generation experiences, and questions of divestment. Campus and community outreach initiatives such as Scholars Working Ambitiously to Graduate or SWAG, the Black women’s support network SISTERS, Breaking Bread and Engaged Cornell are examples of the many efforts currently underway that may help address some aspects of these issues, realizing there no quick fixes – it’s a learning and growing process for all.  We are making progress, even though we still have quite a way to go.  Hopefully, when my grandson arrives in a few years, his experience will be one where he can pursue his studies in an environment where he is at ease, engaged and fulfilled.",
    p44: "Dr. Jacqueline Davis-Manigaulte ’72 was a freshman and member the Afro-American Society at the time of the Willard Straight Hall takeover. She is a Senior Extension Associate with Cornell University Cooperative Extension in New York City where she serves has the Director of Community Relations and Program Leader for Family and Youth Development."
  },
  ];

export default opedscontent;
